# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_FmIndex', [dirname(__file__)])
        except ImportError:
            import _FmIndex
            return _FmIndex
        if fp is not None:
            try:
                _mod = imp.load_module('_FmIndex', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _FmIndex = swig_import_helper()
    del swig_import_helper
else:
    import _FmIndex
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class FmIndex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FmIndex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FmIndex, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _FmIndex.new_FmIndex(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _FmIndex.delete_FmIndex
    __del__ = lambda self: None

    def Seq(self):
        return _FmIndex.FmIndex_Seq(self)

    def getBaseRep(self):
        return _FmIndex.FmIndex_getBaseRep(self)

    def getStore(self):
        return _FmIndex.FmIndex_getStore(self)

    def CreateIndex(self, nBucketSize, nMarkFreq):
        return _FmIndex.FmIndex_CreateIndex(self, nBucketSize, nMarkFreq)

    def CreateSortedArray(self):
        return _FmIndex.FmIndex_CreateSortedArray(self)

    def RebuildOcc(self, bucketSize):
        return _FmIndex.FmIndex_RebuildOcc(self, bucketSize)

    def Occ(self, c_bit, c_index, pos):
        return _FmIndex.FmIndex_Occ(self, c_bit, c_index, pos)

    def Locate(self, i):
        return _FmIndex.FmIndex_Locate(self, i)

    def InitLookup(self, c_bit, out_sp, out_ep):
        return _FmIndex.FmIndex_InitLookup(self, c_bit, out_sp, out_ep)

    def Lookup(self, cur_sp, cur_ep, c_bit, out_sp, out_ep):
        return _FmIndex.FmIndex_Lookup(self, cur_sp, cur_ep, c_bit, out_sp, out_ep)

    def SearchSeq(self, seq, max_match=50):
        return _FmIndex.FmIndex_SearchSeq(self, seq, max_match)

    def CheckSeq(self, seq):
        return _FmIndex.FmIndex_CheckSeq(self, seq)

    def Save(self, fn):
        return _FmIndex.FmIndex_Save(self, fn)

    def Load(self, fn):
        return _FmIndex.FmIndex_Load(self, fn)

    def GetLocateChr(self, i):
        return _FmIndex.FmIndex_GetLocateChr(self, i)

    def GetLocateStrand(self, i):
        return _FmIndex.FmIndex_GetLocateStrand(self, i)
FmIndex_swigregister = _FmIndex.FmIndex_swigregister
FmIndex_swigregister(FmIndex)

# This file is compatible with both classic and new-style classes.


